# Generated by Django 4.2.5 on 2023-10-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizBaslik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='QuizSorulari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icerik', models.CharField(max_length=255)),
                ('secenek1', models.CharField(max_length=255)),
                ('secenek2', models.CharField(max_length=255)),
                ('secenek3', models.CharField(max_length=255)),
                ('secenek4', models.CharField(max_length=255)),
                ('dogru_secenek', models.CharField(max_length=1)),
            ],
        ),
    ]
