# Generated by Django 4.2.5 on 2023-10-18 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_quizsorulari_dogru_secenek'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsorulari',
            name='baslik',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.quizbaslik'),
        ),
    ]
