# Generated by Django 4.2.5 on 2023-10-19 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurslar', '0005_alter_kategori_slug'),
        ('quiz', '0004_quizsorulari_baslik'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizbaslik',
            name='navkbaslik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kurslar.kbaslik'),
        ),
    ]
