# Generated by Django 4.2.5 on 2023-10-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurslar', '0002_kategori_referanceactive_kategori_tutorialactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategori',
            name='referanceBaslik',
            field=models.BooleanField(default=False),
        ),
    ]
