# Generated by Django 4.2.5 on 2023-10-11 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurslar', '0003_kategori_referancebaslik'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kbaslik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='kategori',
            name='kbaslik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kurslar.kbaslik'),
        ),
    ]
