# Generated by Django 4.2.5 on 2023-10-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurslar', '0004_kbaslik_kategori_kbaslik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategori',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
